AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an Amazon ECR repository.'

Parameters:
  RepositoryName:
    Type: String
    Description: 'The name of the ECR repository to create.'

Resources:
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  RepositoryUri:
    Description: 'The URI of the created ECR repository.'
    Value: !GetAtt ECRRepository.RepositoryUri
