# AWSTemplateFormatVersion: '2010-09-09'
# Description: 'CloudFormation template to create an AWS Service Catalog portfolio and a product for creating an S3 bucket.'

# Resources:
#   # Crear el portafolio de Service Catalog
#   ServiceCatalogPortfolio:
#     Type: "AWS::ServiceCatalog::Portfolio"
#     Properties:
#       DisplayName: "S3 Bucket Portfolio"
#       ProviderName: "YourCompanyName"
#       Description: "Portafolio General"

# Outputs:
#   PortfolioId:
#     Description: "The ID of the created Service Catalog portfolio."
#     Value: !Ref ServiceCatalogPortfolio
#   ProductId:
#     Description: "The ID of the created Service Catalog product."
#     Value: !Ref ServiceCatalogProduct
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ServiceCatalogPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties: 
      DisplayName: "Portafolio General"
      ProviderName: "ProveedorDeEjemplo"
      Description: "Portafolio de ejemplo para Service Catalog"

Outputs:
  PortfolioId:
    Description: "ID del Portafolio para asociar productos."
    Value: !Ref ServiceCatalogPortfolio
    Export:
      Name: "PortfolioId"