AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ServiceCatalogPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties: 
      DisplayName: "Portafolio General"
      ProviderName: "ProveedorDeEjemplo"
      Description: "Portafolio de ejemplo para Service Catalog"

Outputs:
  PortfolioId:
    Description: "ID del Portafolio para asociar productos."
    Value: !Ref ServiceCatalogPortfolio
    Export:
      Name: "PortfolioId"