AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an IAM user with specified policies.'

Parameters:
  UserName:
    Type: String
    Description: 'The name of the IAM user to create.'
  
  RoleType:
    Type: String
    Description: 'Select the type of role for the IAM user.'
    AllowedValues:
      - Admin
      - Devs
    Default: Admin

Resources:
  IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref UserName

  # Conditional Admin Access Policy
  AdminAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: IsAdmin
    Properties:
      ManagedPolicyName: 'AdministratorAccess'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'

  # Devs Access Policy
  DevAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: IsDev
    Properties:
      ManagedPolicyName: 'DeveloperAccess'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:Describe*'
              - 's3:List*'
              - 'cloudwatch:PutMetricData'
            Resource: '*'

  # Attach Admin Policy to user
  AttachAdminPolicy:
    Type: 'AWS::IAM::UserToGroupAddition'
    Condition: IsAdmin
    Properties:
      GroupName: 'Admin'
      Users: 
        - !Ref IAMUser

  # Attach Dev Policy to user
  AttachDevPolicy:
    Type: 'AWS::IAM::UserToGroupAddition'
    Condition: IsDev
    Properties:
      GroupName: 'Devs'
      Users: 
        - !Ref IAMUser

Conditions:
  IsAdmin: !Equals [!Ref RoleType, Admin]
  IsDev: !Equals [!Ref RoleType, Devs]

Outputs:
  IAMUserName:
    Description: 'The name of the created IAM user.'
    Value: !Ref IAMUser
  IAMUserArn:
    Description: 'The ARN of the created IAM user.'
    Value: !GetAtt IAMUser.Arn
